# Generated by Django 4.2.7 on 2026-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_email_c80f75_idx',
            old_name='users_custo_email_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_role_6a37b1_idx',
            old_name='users_custo_role_123456_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
