# Generated by Django 4.2.7 on 2026-04-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField()),
                ('tesseract_version', models.CharField(blank=True, max_length=50)),
                ('language_detected', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='schedules/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('parsed_tasks_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='uploads.scheduleupload'),
        ),
        migrations.AddIndex(
            model_name='scheduleupload',
            index=models.Index(fields=['uploaded_by', 'status'], name='uploads_sch_uploade_250e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleupload',
            index=models.Index(fields=['created_at'], name='uploads_sch_created_0580ce_idx'),
        ),
    ]
